### ISSUE TITLE
Google Play Console

### ISSUE THREAD

**Issue by kurwjan** [alessioC42/SPH-vertretungsplan#16]
*(Ich habe noch keinen Zugang, aber sehr bald einen.)*

Ich möchte gerne diese App auf den Play Store sehen, obwohl es noch in einer sehr frühen Phase ist (man kann das ja auch als Pre-Release hochladen). Ich hatte auch mal Erfahrung mit Flutter und Dart in der Vergangenheit, somit möchte ich auch irgendwann mithelfen, nachdem ich mein Python-Projekt _([LanisAPI](https://github.com/kurwjan/LanisAPI))_ in eine stabile Version gebracht habe.

### Wieso?
Diese App sieht am aktivsten aus von der Aktivität und das Kotlin-Projekt von @koenidv ist einfach zu massiv um es wiederzubeleben.
Außerdem wollte ich eigentlich eine eigene App machen, indem ich Frontend mit FastAPI mit meinen Python-Projekt verbinde, aber man muss ja nicht alles immer erneut anfangen.

### Mögliche Probleme
Das wird ja eigentlich unter meinen Developer-Namen _(kurwjan)_ veröffentlicht, somit weißt ich nicht wie das mit dem Vertrauen funktioniert, weil eigentlich bin ich irgendein Random Dude aus dem Internet.

**Mit dem Hochladen auf dem Play Store kann man dann bestimmt mehr Personen erreichen und somit mehr Bugs herausfinden und etc.**

**Comment by alessioC42** [comment]
Ja, die Play Console hat (glaube ich) sehr gute Bug Hunting Funktionen. Ich habe auch von den meisten Leuten aus meiner Klasse gehört, dass sie die App unbedingt im Play Store haben wollen. (Die wollen das finanzieren und da sage ich nicht nein :D)
Also das mit dem Zugang werde ich wahrscheinlich sehr bald selber haben. 
Es wäre echt cool, wenn sich noch mehr Leute an dem Projekt beteiligen würden, denn mehr als eine Schule als Testbasis zu haben ist viel besser als nur meine. (Ich verstehe bis heute nicht wirklich, wieso einige Features nur von meiner Schule ünterstützt werden. Es ist einf komisch)
Wenn du willst, können wir mal über Discord quatschen.

**Comment by kurwjan** [comment]
Gut dann muss ich nicht 25$ ausgeben und ja deutsche Schulen sind bei Technologie manchmal merkwürdig. Bei Discord heiße ich genauso wie auf Github, den Tag haben sie ja leider entfernt.
